(venv) root@debianThesis:/mnt/shared/fuseSandbox# python3 fuseSandbox.py "firefox" "/mnt/fuse_mount" "fuse-overlayfs -o lowerdir=/,upperdir=/mnt/fuse_mount,workdir=/mnt/fuse_work" --debug
Traceback (most recent call last):
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 53, in <module>
    from namespace_launcher import setup_uid_gid_maps
ImportError: cannot import name 'setup_uid_gid_maps' from 'namespace_launcher' (/mnt/shared/fuseSandbox/sandbox_scripts/namespace_launcher.py)
(venv) root@debianThesis:/mnt/shared/fuseSandbox# 

(venv) root@debianThesis:/mnt/shared/fuseSandbox# python3 fuseSandbox.py "firefox" "/mnt/fuse_mount" "fuse-overlayfs -o lowerdir=/,upperdir=/mnt/fuse_mount,workdir=/mnt/fuse_work" --debug
Traceback (most recent call last):
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 49, in <module>
    from namespace_launcher import setup_uid_gid_maps
ImportError: cannot import name 'setup_uid_gid_maps' from 'namespace_launcher' (/mnt/shared/fuseSandbox/sandbox_scripts/namespace_launcher.py)

(venv) root@debianThesis:/mnt/shared/fuseSandbox# python3 fuseSandbox.py "firefox" "/mnt/fuse_mount" "fuse-overlayfs -o lowerdir=/,upperdir=/mnt/fuse_mount,workdir=/mnt/fuse_work" --debug
[DEBUG] Laden der Policy-Datei: /mnt/shared/fuseSandbox/policies/default_policy.json
[DEBUG] Inhalt der Policy-Datei:
{
  "allow_network": true,
  "readable_paths": [
    "/tmp"
  ],
  "writable_paths": [
    "/tmp"
  ],
  "executable_paths": [],
  "restricted_paths": [
    "/home",
    "/etc",
    "/usr",
    "/bin"
  ],
  "bubblewrap_params": [
    "--dev-bind",
    "/",
    "/",
    "--bind",
    "/mnt/fuse_mount",
    "/root",
    "--unshare-all",
    "--proc",
    "/proc",
    "--dir",
    "/tmp",
    "--share-net"
  ]
}
[DEBUG] Laden der Policy-Datei: /mnt/shared/fuseSandbox/policies/default_policy.json
[DEBUG] Inhalt der Policy-Datei:
{
  "allow_network": true,
  "readable_paths": [
    "/tmp"
  ],
  "writable_paths": [
    "/tmp"
  ],
  "executable_paths": [],
  "restricted_paths": [
    "/home",
    "/etc",
    "/usr",
    "/bin"
  ],
  "bubblewrap_params": [
    "--dev-bind",
    "/",
    "/",
    "--bind",
    "/mnt/fuse_mount",
    "/root",
    "--unshare-all",
    "--proc",
    "/proc",
    "--dir",
    "/tmp",
    "--share-net"
  ]
}
[DEBUG] Network access allowed
[DEBUG] Readable paths: ['/tmp']
[DEBUG] Writable paths: ['/tmp']
[DEBUG] Executable paths: []
[DEBUG] Restricted paths: ['/home', '/etc', '/usr', '/bin']
[DEBUG] Bubblewrap parameters: ['--dev-bind', '/', '/', '--bind', '/mnt/fuse_mount', '/root', '--unshare-all', '--proc', '/proc', '--dir', '/tmp', '--share-net']
[DEBUG] Erstellen des FUSE-Mountpoints: /mnt/fuse_mount
[DEBUG] Starten des FUSE-Dateisystems mit dem Befehl: fuse-overlayfs -o lowerdir=/,upperdir=/mnt/fuse_mount,workdir=/mnt/fuse_work
unknown argument ignored: lazytime
[DEBUG] Starting application ['firefox'] in a sandbox...
[DEBUG] Bubblewrap command: bwrap --dev-bind / / --bind /mnt/fuse_mount /root --dev-bind / / --bind /mnt/fuse_mount /root --unshare-all --proc /proc --dir /tmp --share-net --userns-block-fd 5 --info-fd 4 firefox
bwrap: --userns-block-fd requires --unshare-user
[DEBUG] Unmounting FUSE filesystem from /mnt/fuse_mount
Unmounted FUSE filesystem from /mnt/fuse_mount
[DEBUG] Unmounting FUSE filesystem from /mnt/fuse_mount
fusermount: failed to unmount /mnt/fuse_mount: Invalid argument
Unmounted FUSE filesystem from /mnt/fuse_mount
Traceback (most recent call last):
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 152, in <module>
    main()
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 149, in main
    launch_application(app_command, args.fuse_mountpoint, args.fuse_command, args.app_policy_file)
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 112, in launch_application
    data = json.load(os.fdopen(info_pipe[0]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)



(venv) root@debianThesis:/mnt/shared/fuseSandbox# python3 fuseSandbox.py "firefox" "/mnt/fuse_mount" "fuse-overlayfs -o lowerdir=/,upperdir=/mnt/fuse_mount,workdir=/mnt/fuse_work" --debug
[DEBUG] Laden der Policy-Datei: /mnt/shared/fuseSandbox/policies/default_policy.json
[DEBUG] Inhalt der Policy-Datei:
{
  "allow_network": true,
  "readable_paths": [
    "/tmp"
  ],
  "writable_paths": [
    "/tmp"
  ],
  "executable_paths": [],
  "restricted_paths": [
    "/home",
    "/etc",
    "/usr",
    "/bin"
  ],
  "bubblewrap_params": [
    "--dev-bind",
    "/",
    "/",
    "--bind",
    "/mnt/fuse_mount",
    "/root",
    "--unshare-all",
    "--proc",
    "/proc",
    "--dir",
    "/tmp",
    "--share-net"
  ]
}
[DEBUG] Laden der Policy-Datei: /mnt/shared/fuseSandbox/policies/default_policy.json
[DEBUG] Inhalt der Policy-Datei:
{
  "allow_network": true,
  "readable_paths": [
    "/tmp"
  ],
  "writable_paths": [
    "/tmp"
  ],
  "executable_paths": [],
  "restricted_paths": [
    "/home",
    "/etc",
    "/usr",
    "/bin"
  ],
  "bubblewrap_params": [
    "--dev-bind",
    "/",
    "/",
    "--bind",
    "/mnt/fuse_mount",
    "/root",
    "--unshare-all",
    "--proc",
    "/proc",
    "--dir",
    "/tmp",
    "--share-net"
  ]
}
[DEBUG] Network access allowed
[DEBUG] Readable paths: ['/tmp']
[DEBUG] Writable paths: ['/tmp']
[DEBUG] Executable paths: []
[DEBUG] Restricted paths: ['/home', '/etc', '/usr', '/bin']
[DEBUG] Bubblewrap parameters: ['--dev-bind', '/', '/', '--bind', '/mnt/fuse_mount', '/root', '--unshare-all', '--proc', '/proc', '--dir', '/tmp', '--share-net']
[DEBUG] Erstellen des FUSE-Mountpoints: /mnt/fuse_mount
[DEBUG] Starten des FUSE-Dateisystems mit dem Befehl: fuse-overlayfs -o lowerdir=/,upperdir=/mnt/fuse_mount,workdir=/mnt/fuse_work
unknown argument ignored: lazytime
[DEBUG] Starting application ['firefox'] in a sandbox...
[DEBUG] Bubblewrap command: bwrap --dev-bind / / --bind /mnt/fuse_mount /root --dev-bind / / --bind /mnt/fuse_mount /root --unshare-all --proc /proc --dir /tmp --share-net --userns-block-fd 5 --info-fd 4 firefox
bwrap: --userns-block-fd requires --unshare-user
[DEBUG] Unmounting FUSE filesystem from /mnt/fuse_mount
Unmounted FUSE filesystem from /mnt/fuse_mount
[DEBUG] Unmounting FUSE filesystem from /mnt/fuse_mount
fusermount: failed to unmount /mnt/fuse_mount: Invalid argument
Unmounted FUSE filesystem from /mnt/fuse_mount
Traceback (most recent call last):
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 152, in <module>
    main()
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 149, in main
    launch_application(app_command, args.fuse_mountpoint, args.fuse_command, args.app_policy_file)
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 112, in launch_application
    data = json.load(os.fdopen(info_pipe[0]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
(venv) root@debianThesis:/mnt/shared/fuseSandbox# python3 fuseSandbox.py "firefox" "/mnt/fuse_mount" "fuse-overlayfs -o lowerdir=/,upperdir=/mnt/fuse_mount,workdir=/mnt/fuse_work" --debug
Traceback (most recent call last):
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 50, in <module>
    from client import run_application_in_sandbox
  File "/mnt/shared/fuseSandbox/sandbox_scripts/client.py", line 5, in <module>
    bus = SessionBus()
          ^^^^^^^^^^^^
  File "/root/venv/lib/python3.11/site-packages/pydbus/bus.py", line 60, in SessionBus
    return bus_get(Bus.Type.SESSION)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.11/site-packages/pydbus/bus.py", line 19, in bus_get
    return Gio.bus_get_sync(type, None).pydbus
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: The connection is closed (18)

(venv) root@debianThesis:/mnt/shared/fuseSandbox# python3 fuseSandbox.py "firefox" "/mnt/fuse_mount" "fuse-overlayfs -o lowerdir=/,upperdir=/mnt/fuse_mount,workdir=/mnt/fuse_work" --debug
Traceback (most recent call last):
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 9, in <module>
    from dbus_scripts.dbus_client import request_permission
  File "/mnt/shared/fuseSandbox/dbus_scripts/dbus_client.py", line 1, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'

(venv) root@debianThesis:/mnt/shared/fuseSandbox# python3 fuseSandbox.py "firefox" "/mnt/fuse_mount" "fuse-overlayfs -o lowerdir=/,upperdir=/mnt/fuse_mount,workdir=/mnt/fuse_work" --debug
Traceback (most recent call last):
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 55, in <module>
    from client import run_application_in_sandbox
  File "/mnt/shared/fuseSandbox/sandbox_scripts/client.py", line 5, in <module>
    bus = SessionBus()
          ^^^^^^^^^^^^
  File "/root/venv/lib/python3.11/site-packages/pydbus/bus.py", line 60, in SessionBus
    return bus_get(Bus.Type.SESSION)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.11/site-packages/pydbus/bus.py", line 19, in bus_get
    return Gio.bus_get_sync(type, None).pydbus
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: The connection is closed (18)


(venv) root@debianThesis:/mnt/shared/fuseSandbox# python3 fuseSandbox.py "firefox" "/mnt/fuse_mount" "fuse-overlayfs -o lowerdir=/,upperdir=/mnt/fuse_mount,workdir=/mnt/fuse_work" --debug
[DEBUG] Laden der Policy-Datei: /mnt/shared/fuseSandbox/policies/default_policy.json
[DEBUG] Inhalt der Policy-Datei:
{
  "allow_network": true,
  "readable_paths": [
    "/tmp"
  ],
  "writable_paths": [
    "/tmp"
  ],
  "executable_paths": [],
  "restricted_paths": [
    "/home",
    "/etc",
    "/usr",
    "/bin"
  ],
  "bubblewrap_params": [
    "--dev-bind",
    "/",
    "/",
    "--bind",
    "/mnt/fuse_mount",
    "/root",
    "--unshare-all",
    "--proc",
    "/proc",
    "--dir",
    "/tmp",
    "--share-net"
  ]
}
[DEBUG] Laden der Policy-Datei: /mnt/shared/fuseSandbox/policies/default_policy.json
[DEBUG] Inhalt der Policy-Datei:
{
  "allow_network": true,
  "readable_paths": [
    "/tmp"
  ],
  "writable_paths": [
    "/tmp"
  ],
  "executable_paths": [],
  "restricted_paths": [
    "/home",
    "/etc",
    "/usr",
    "/bin"
  ],
  "bubblewrap_params": [
    "--dev-bind",
    "/",
    "/",
    "--bind",
    "/mnt/fuse_mount",
    "/root",
    "--unshare-all",
    "--proc",
    "/proc",
    "--dir",
    "/tmp",
    "--share-net"
  ]
}
[DEBUG] Network access allowed
[DEBUG] Readable paths: ['/tmp']
[DEBUG] Writable paths: ['/tmp']
[DEBUG] Executable paths: []
[DEBUG] Restricted paths: ['/home', '/etc', '/usr', '/bin']
[DEBUG] Bubblewrap parameters: ['--dev-bind', '/', '/', '--bind', '/mnt/fuse_mount', '/root', '--unshare-all', '--proc', '/proc', '--dir', '/tmp', '--share-net']
[DEBUG] Erstellen des FUSE-Mountpoints: /mnt/fuse_mount
[DEBUG] Starten des FUSE-Dateisystems mit dem Befehl: fuse-overlayfs -o lowerdir=/,upperdir=/mnt/fuse_mount,workdir=/mnt/fuse_work
unknown argument ignored: lazytime
[DEBUG] Starting application ['firefox'] in a sandbox...
[DEBUG] Bubblewrap command: --dev-bind / / --bind /mnt/fuse_mount /root --unshare-all --proc /proc --dir /tmp --share-net --bind /mnt/fuse_mount /root firefox --userns-block-fd 5 --info-fd 4 firefox
[DEBUG] Unmounting FUSE filesystem from /mnt/fuse_mount
fusermount: failed to unmount /mnt/fuse_mount: Device or resource busy
Unmounted FUSE filesystem from /mnt/fuse_mount
[DEBUG] Unmounting FUSE filesystem from /mnt/fuse_mount
fusermount: failed to unmount /mnt/fuse_mount: Device or resource busy
Unmounted FUSE filesystem from /mnt/fuse_mount
Traceback (most recent call last):
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 154, in <module>
    main()
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 151, in main
    launch_application(app_command, args.fuse_mountpoint, args.fuse_command, args.app_policy_file)
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 106, in launch_application
    os.execvp(bwrap_command[0], bwrap_command)
  File "<frozen os>", line 574, in execvp
  File "<frozen os>", line 616, in _execvpe
  File "<frozen os>", line 607, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory
[DEBUG] Unmounting FUSE filesystem from /mnt/fuse_mount
Unmounted FUSE filesystem from /mnt/fuse_mount
[DEBUG] Unmounting FUSE filesystem from /mnt/fuse_mount
fusermount: failed to unmount /mnt/fuse_mount: Invalid argument
Unmounted FUSE filesystem from /mnt/fuse_mount
Traceback (most recent call last):
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 154, in <module>
    main()
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 151, in main
    launch_application(app_command, args.fuse_mountpoint, args.fuse_command, args.app_policy_file)
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 111, in launch_application
    data = json.load(os.fdopen(info_pipe[0]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


[DEBUG] Unmounting FUSE filesystem from /mnt/fuse_mount
fusermount: failed to unmount /mnt/fuse_mount: Invalid argument
Unmounted FUSE filesystem from /mnt/fuse_mount
Traceback (most recent call last):
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 156, in <module>
    main()
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 153, in main
    launch_application(app_command, args.fuse_mountpoint, args.fuse_command, args.app_policy_file)
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 113, in launch_application
    data = json.load(os.fdopen(info_pipe[0]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


[DEBUG] Unmounting FUSE filesystem from /mnt/fuse_mount
fusermount: failed to unmount /mnt/fuse_mount: Invalid argument
Unmounted FUSE filesystem from /mnt/fuse_mount
Traceback (most recent call last):
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 157, in <module>
    main()
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 154, in main
    launch_application(app_command, args.fuse_mountpoint, args.fuse_command, args.app_policy_file)
  File "/mnt/shared/fuseSandbox/fuseSandbox.py", line 119, in launch_application
    setup_uid_gid_maps(data['child-pid'], os.getuid(), os.getgid())
TypeError: setup() takes 2 positional arguments but 3 were given
